sudo: false
language: python
python:
  - 2.6
  - 2.7
services:
  - redis
env:
  - FLASK=0.10.1
  - FLASK=0.9
  - FLASK=0.8.1
  - FLASK=0.7.2
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r dev_requirements.txt
  - pip install -q -e .
script:
  - python setup.py test
