language: python
python:
  - 2.6
  - 2.7
env:
  - FLASK=0.8
  - FLASK=0.7
install:
  - pip install -q Flask==$FLASK --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
